development:
  host: localhost
  adapter: postgresql
  database: web-interface_development
  pool: 5
  username: web-interface
  password: web-interface

test:
  host: localhost
  adapter: postgresql
  database: web-interface_test
  pool: 5
  username: web-interface
  password: web-interface
